name: CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ node-version }}

    - name: Setup pnpm
      uses: pnpm/action-setup@v2.2.4
      with:
        version: latest
        run_install: true
        
    - name: Build
      run: pnpm build

    - name: Upload artifact for Pages
      uses: actions/upload-pages-artifact@v1.0.8
      with:
        path: build/
      
  Deploy:
    needs: Build
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2.0.1
